### ISSUE TITLE
Improve your README.md

### ISSUE THREAD

**Issue by Souravirus** [srbcheema1/dfr#3]
Improve your README.md. you just don't write full form in your README.md. Where are the installation step. Where is the contribution guide. Just improve the documentation please.

**Comment by vishichoudhary** [comment]
or you can take reference from https://github.com/vishichoudhary/anotherCollegeShit/blob/master/README.md

**Comment by srbcheema1** [comment]
hi @souravirus and @vishichoudhary
 glad that you visited our repository. Right now our tool is in alpha state and we are not yet encouraging developers to build and use the tool right now. i will update the README and build details as soon as we are ready with our first release. 
thanks for the consideration.
stay tuned. happy coding.

**Comment by srbcheema1** [comment]
we haven't launched our product so there should be no question about tech support. talking about our codebase  ... its basically a simple repository, but you have to be a genius to understand its simplicity.

**Comment by nimitbhardwaj** [comment]
But why kts open source now, if its in alpha stage, just close source it do your work.

**Comment by Souravirus** [comment]
@nimitbhardwaj please have a look at definition of open source
-srbcheema1

**Comment by nimitbhardwaj** [comment]
Why should i, i dont like this crab

**Comment by Souravirus** [comment]
I also don't like it. But please wait for @Spider34 before reaching any conclusions.

**Comment by srbcheema1** [comment]
Hi @Souravirus I have updated the README file. now it is quite easy to build the tool locally.
