### ISSUE TITLE
Put A .gitignore 

### ISSUE THREAD

**Issue by Souravirus** [srbcheema1/dfr#4]
Please put a . gitignore file in your repository. There should not be random images in your repository. This increases the total size of the project. We face difficulties while cloning the project.
Regards
Sourav

**Comment by nimitbhardwaj** [comment]
Yes I agree, its very foolish design, no model is used to describe workflow

**Comment by srbcheema1** [comment]
added .gitignore thanks @Souravirus @nimitbhardwaj for the valuable feedback
